# ! /bin/bash
# mod +x ig-blogger-scrape.sh
# ./ig-blogger-scrape.sh

declare -a ig_handle=(
# 'muradosmann'
# 'doyoutravel'
# 'gypsea_lust'
# 'loki'
# 'taramilktea'
# 'worldwanderlust'
# 'theblondeabroad'
# 'jess.wandering'
# 'missholldoll'
# 'expertvagabond'
# 'bruisedpassport'
# 'finduslost'
# 'Vagablonde_laura'
# 'mappingmegan'
# 'shivya'
# 'jannikobenhoff'
# 'AlexStrohl'
# 'erubes1'
# 'chrisburkard'
# 'Doyoutravel'
# 'sennarelax'
# 'Eljackson'
# 'Swedishnomad'
# 'mag91105'
# 'vancitywild'
# 'Danielkordan'
# 'EverChangingHorizon'
# 'Chelseakauai'
# 'mrbenbrown'
# 'celinnedacosta'
# 'lostleblanc'
# 'andyto'
# 'Jordhammond'
# 'migrationology'
# 'damonandjo'
# 'Saltinourhair'
# 'booyasan'
# 'WanderReds'
# 'sayingyesis'
# 'mena_shootz'
# 'FunForLouis'
# 'kyrenian'
# 'Chloe_T'
# 'Lebackpacker'
# 'californiathroughmylens'
'jackharries'
'drinksintheair'
'JeremyJauncey'
'tiffpenguin'
'Travisburkephotography'
'sunshinestories'
'annapurnauna'
'BrendanVanSon'
'kenkaminesky'
'codycobb'
'poker_nomad'
'glographics'
'PassionPassport'
'brahmino'
'Alienchrisblog'
'Mylifesatravelmovie'
'Theblondeabroad'
'leaveyourdailyhell'
'globeguide'
'golden_heart'
'marianapostcards'
'journey_driven'
'2straws'
'theupbeatpath'
'oldkyrenian'
'Emitoms'
'LesleyAnneMurphy'
'the_candourist'
'lucylaucht'
'lifeofsabin'
'uncornered_market'
'framesbyjustinjames'
'theworldpursuit'
'bucketlistjourney'
'bontraveler'
'SamHorine'
'beard_and_curly'
'nodestinations'
'girlvsglobe'
'LeeAbbamonte'
'Traveltomtom'
'laurenswells'
'Tourist2Townie'
'Triphackr'
'Youngadventuress'
'DrewBinsky'
'Laurenepbath'
'theplanetd'
'et_voila__'
'abel.j.rojas'
'iamdocgelo'
'Gettingstamped'
'travelbabbo'
'i_am_aileen'
'michidipp'
'Anna.Everywhere'
'thattravelblog'
'goldie_berlin'
'ordinarytraveler'
'Bemytravelmuse'
'jonathan_irish'
'jamesasquithtravel'
'sassychris1'
'roundtheworldgirl'
'mthiessen'
'landlopers'
'thejetsetterdiaries'
'Kirstenalana'
)

## now loop through the above array
for i in "${ig_handle[@]}"
do
   echo "scraping IG: $i"
   instagram-scraper $i -u mids.nomadiq -p mids2019 --include-location --media-types none
   #instagram-scraper mappingmegan -u mids.w210 -p mids2019 --include-location --media-types none
   sleep 60
done

find . -iname '*.json' -execdir mv {} .. \;

